{{- if .Values.database.remoteSecretKey }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "app-cluster1-deploy.fullname" . }}-database
  labels:
    {{- include "app-cluster1-deploy.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.database.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.database.secretStore.name }}
    kind: {{ .Values.database.secretStore.kind }}
  target:
    name: {{ .Values.database.secretName }}
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        url: "postgresql+psycopg://{{ `{{ .username }}` }}:{{ `{{ .password }}` }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}"
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.database.remoteSecretKey | quote }}
        property: username
    - secretKey: password
      remoteRef:
        key: {{ .Values.database.remoteSecretKey | quote }}
        property: password
{{- end }}
