environment: dev
clusterName: cluster1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: false
  name: default

backend:
  replicas: 2
  image:
    repository: chnadranavinn/deployboard-backend
    tag: replace-with-git-sha
    pullPolicy: IfNotPresent
  containerPort: 8000
  servicePort: 8000
  resources:
    requests: {cpu: 100m, memory: 128Mi}
    limits: {cpu: 500m, memory: 512Mi}
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80

frontend:
  replicas: 2
  image:
    repository: chnadranavinn/deployboard-frontend
    tag: replace-with-git-sha
    pullPolicy: IfNotPresent
  containerPort: 8080
  servicePort: 80
  resources:
    requests: {cpu: 50m, memory: 64Mi}
    limits: {cpu: 250m, memory: 256Mi}
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80

database:
  name: deployboard_dev
  host: deployboard-dev-postgres.cpoa0cqk2345.ap-south-1.rds.amazonaws.com
  port: 5432
  secretName: deployboard-database
  remoteSecretKey: arn:aws:secretsmanager:ap-south-1:073771271034:secret:rds!db-383de0ec-5a68-4bd4-9fc0-a12cccdc7495-FmLSdM
  refreshInterval: 1h
  secretStore:
    name: aws-secrets-manager
    kind: ClusterSecretStore

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: deployboard.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

httpRoute:
  enabled: false
  annotations: {}
  parentRefs: [{name: gateway, sectionName: http}]
  hostnames: [deployboard.example.com]
