apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deployboard.fullname" . }}-frontend
  labels:
    {{- include "deployboard.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      {{- include "deployboard.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "deployboard.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: frontend
          image: "{{ .Values.images.frontend.repository }}:{{ .Values.images.frontend.tag }}"
          imagePullPolicy: {{ .Values.images.frontend.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: BACKEND_HOST
              value: {{ include "deployboard.fullname" . }}-backend
            - name: BACKEND_PORT
              value: {{ .Values.backend.service.port | quote }}
            - name: API_URL
              value: ""
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "deployboard.fullname" . }}-frontend
  labels:
    {{- include "deployboard.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    {{- include "deployboard.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
